controllers_security:
    resource: ../../src/Controller/Security
    type: annotation

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation

controllers_connect:
    resource: ../../src/Controller/Connect
    type: annotation

controllers_complete:
    resource: ../../src/Controller/Profile
    name_prefix: profile_
    type: annotation

controllers_publication:
    resource: ../../src/Controller/Publication
    type: annotation

controllers_comment:
    resource: ../../src/Controller/Comment
    type: annotation

controllers_search:
    resource: ../../src/Controller/Search
    name_prefix: search_
    type: annotation

controllers_event:
    resource: ../../src/Controller/Event
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
