vich_uploader:
    db_driver: orm

    mappings:
        image_profile:
            uri_prefix: '%app.path.image_profile%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_profile%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        couverture_profile:
            uri_prefix: '%app.path.couverture_profile%'
            upload_destination: '%kernel.project_dir%/public/%app.path.couverture_profile%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
